services:
  wordpress:
    container_name: wordpress-prac
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./dist/data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - database
    networks:
      - wordpress-practice
    restart: unless-stopped

  database:
    container_name: mysql-prac
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "wordpress"
    ports:
      - 3307:3306
    volumes:
      - ./dist/db:/var/lib/mysql
    networks:
      - wordpress-practice

networks:
  wordpress-practice:
